version: '3.5'

services:

  burrow:
    container_name: dab_burrow
    image: 'nekroze/burrow:latest'
    labels:
      description: 'Kafka Consumer Lag Checking'
      com.centurylinklabs.watchtower.enable: 'true'
    environment:
        BURROW_ZOOKEEPER_SERVERS: "${DAB_APPS_BURROW_TARGET_ZOOKEEPER:-zookeeper}:2181"
        BURROW_CLUSTER_LOCAL_SERVERS: "${DAB_APPS_BURROW_TARGET_KAFKA:-kafka}:9092"
        BURROW_CONSUMER_LOCAL_SERVERS: "${DAB_APPS_BURROW_TARGET_KAFKA:-kafka}:9092"
        BURROW_CONSUMER_LOCAL_GROUP-BLACKLIST: '^(console-consumer-|python-kafka-consumer-).*$$'
        BURROW_CONSUMER_LOCAL_ZK_SERVERS: "${DAB_APPS_BURROW_TARGET_ZOOKEEPER:-zookeeper}:2181"
        BURROW_CONSUMER_LOCAL_ZK_GROUP-BLACKLIST: '^(console-consumer-|python-kafka-consumer-).*$$'
    depends_on:
      - kafka
      - zookeeper
    networks:
      - default
      - lab
    expose:
      - 8000
    restart: on-failure

networks:
  default:
    name: dab_apps
  lab:
    external:
      name: lab
